# yaml-language-server: $schema=https://raw.githubusercontent.com/Azure/azure-dev/main/schemas/v1.0/azure.yaml.json

name: rag-sharepoint

# Infrastructure configuration
infra:
  provider: bicep
  path: infra
  module: main

services:
  rag-functions:
    project: ./app
    language: py
    host: function
    resourceGroup: ${FUNCTION_DEPLOY_RESOURCE_GROUP}
    resourceName: ${FUNCTION_DEPLOY_APP_NAME}

# Pipeline configuration for CI/CD
pipeline:
  provider: github
